#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

if [[ -s "~/.zcompdump" ]]; then
  rm "~/.zcompdump"
fi

# Customize to your needs...

export PATH=/usr/local/bin:/usr/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin
export PATH="/usr/local/opt/imagemagick@6/bin/:$PATH"
export NVM_DIR="$HOME/.nvm"
export EDITOR=vim
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
export GPG_TTY=$(tty)

source ~/.alias
source /usr/local/opt/nvm/nvm.sh

autoload edit-command-line
zle -N edit-command-line
bindkey '^Xe' edit-command-line

which rbenv >/dev/null 2>&1 && eval "$(rbenv init -)"
which pyenv >/dev/null 2>&1 && eval "$(pyenv init -)"

archey -c -o
